const multiFormData = [
  {
    formName: "profileform",
    action: "#",
    method: "GET",
    classNames: "row g-3 was-validated",
    title: "Personal Information",
    subtitile: "",
    text: "Sign up Details",
    fields: [
      {
        field: "InputBox",
        data: {
          label: "Telephone",
          type: "number",
          fieldname: "telephone",
          parentClass: "col-md-6",
          classNames: "form-control",
          id: "",
          placeholder: "please enter your telephone number",
          defaultValue: "",
          min: 1,
          max: 9999999999,
          minLength: 4,
          maxLength: 30,
          // Pattern: "",
          readonly: false,
          required: true,
          title: "emailid",
        },
      },
      {
        field: "InputBox",
        data: {
          label: "Mobile No",
          type: "number",
          fieldname: "mobileno",
          parentClass: "col-md-6",
          classNames: "form-control",
          id: "",
          placeholder: "please enter your mobile number",
          defaultValue: "",
          min: 1,
          max: 9999999999,
          minLength: 4,
          maxLength: 30,
          // Pattern: "",
          readonly: false,
          required: true,
          title: "mobileno",
        },
      },
      {
        field: "InputBox",
        data: {
          label: "Country Name",
          type: "text",
          fieldname: "countryname",
          parentClass: "col-md-6",
          classNames: "form-control",
          id: "",
          placeholder: "please enter your contryname",
          defaultValue: "",
          min: 1,
          max: 9999999999,
          minLength: 4,
          maxLength: 30,
          // Pattern: "",
          readonly: false,
          required: true,
          title: "countryname",
        },
      },
    /*   {
        field: "CheckBox",
        data: {
          label: "framework list",
          type: "checkbox",
          fieldname: "frameworks",
          parentClass: "col-md-12",
          classNames: "form-check-input",
          id: "",
          defaultValue: "",
          readonly: false,
          required: true,
          list: [
            "By signing up, you agree to our Terms, Data Policy and Cookies Policy.",
          ],
        },
      },
        {
        field: "CheckBox",
        data: {
          label: "Check box list",
          type: "radio",
          fieldname: "framework",
          parentClass: "col-md-6",
          classNames: "form-check-input",
          id: "",
          defaultValue: "",
          readonly: false,
          required: true,
          list: ["React", "Node", "Angular", "UI", "Responsive"],
        },
      }, 
       {
       field: "TextareaBox",
       data: {
         label: "Description",
         fieldname: "description",
         parentClass: "col-md-12",
         classNames: "form-control",
         id: "",
         placeholder: "please enter your description",
         defaultValue: "",
         rows: 2,
         min: 4,
         max: 30,
         minLength: 4,
         maxLength: 30,
           Pattern: "",
         readonly: false,
         required: true,
         title: "description",
       },
     },
     */
      {
        field: "ButtonBox",
        data: {
          type: "button",
          fieldname: "buttonLogin",
          parentClass: "col-md-12 mt-2",
          classNames: "btn btn-primary",
          id: "",
          defaultValue: "Save",
          readonly: false,
        },
      },
    ],
  },
];
export default multiFormData;
